package com.zipgallery.app.ui.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.platform.LocalContext
import com.zipgallery.app.model.AppThemeMode
import kotlin.math.pow

/**
 * Baseline Material 3 schemes for a teal brand seed (#00696D) — a nod to the
 * photographic / cyanotype world of a gallery app. Values follow the M3 tonal
 * palettes generated by Material Theme Builder for this seed and are used when
 * dynamic color (Material You) is disabled or unavailable (pre-Android 12).
 */
private val LightColorScheme = lightColorScheme(
    primary = Color(0xFF00696D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF9CF1F5),
    onPrimaryContainer = Color(0xFF002022),
    secondary = Color(0xFF4A6365),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE8EA),
    onSecondaryContainer = Color(0xFF051F21),
    tertiary = Color(0xFF555F71),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDAE2F9),
    onTertiaryContainer = Color(0xFF121C31),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFAFDFD),
    onBackground = Color(0xFF191C1C),
    surface = Color(0xFFFAFDFD),
    onSurface = Color(0xFF191C1C),
    surfaceVariant = Color(0xFFDAE4E5),
    onSurfaceVariant = Color(0xFF3F4949),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F7F7),
    surfaceContainer = Color(0xFFEEF2F2),
    surfaceContainerHigh = Color(0xFFE8ECEC),
    surfaceContainerHighest = Color(0xFFE2E6E6),
    outline = Color(0xFF6F7979),
    outlineVariant = Color(0xFFBEC8C9),
    inverseSurface = Color(0xFF2D3131),
    inverseOnSurface = Color(0xFFEFF1F1),
    inversePrimary = Color(0xFF7AD6DB),
    scrim = Color(0xFF000000)
)

private val DarkColorScheme = darkColorScheme(
    primary = Color(0xFF7AD6DB),
    onPrimary = Color(0xFF003739),
    primaryContainer = Color(0xFF004F52),
    onPrimaryContainer = Color(0xFF9CF1F5),
    secondary = Color(0xFFB1CCCE),
    onSecondary = Color(0xFF1B3436),
    secondaryContainer = Color(0xFF324B4D),
    onSecondaryContainer = Color(0xFFCCE8EA),
    tertiary = Color(0xFFBEC6DC),
    onTertiary = Color(0xFF283141),
    tertiaryContainer = Color(0xFF3E4759),
    onTertiaryContainer = Color(0xFFDAE2F9),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF101414),
    onBackground = Color(0xFFDFE4E4),
    surface = Color(0xFF101414),
    onSurface = Color(0xFFDFE4E4),
    surfaceVariant = Color(0xFF3F4949),
    onSurfaceVariant = Color(0xFFBEC8C9),
    surfaceContainerLowest = Color(0xFF0B0F0F),
    surfaceContainerLow = Color(0xFF191C1C),
    surfaceContainer = Color(0xFF1D2020),
    surfaceContainerHigh = Color(0xFF272B2B),
    surfaceContainerHighest = Color(0xFF323636),
    outline = Color(0xFF889293),
    outlineVariant = Color(0xFF3F4949),
    inverseSurface = Color(0xFFDFE4E4),
    inverseOnSurface = Color(0xFF2D3131),
    inversePrimary = Color(0xFF00696D),
    scrim = Color(0xFF000000)
)

/** WCAG AA minimum contrast ratio for normal-size text. */
private const val MIN_TEXT_CONTRAST_RATIO = 4.5

/** Relative luminance of a color in the [0, 1] range (WCAG 2.x definition). */
private fun Color.luminance(): Double {
    fun channel(c: Float): Double {
        val v = c.toDouble()
        return if (v <= 0.03928) v / 12.92 else ((v + 0.055) / 1.055).pow(2.4)
    }
    return 0.2126 * channel(red) + 0.7152 * channel(green) + 0.0722 * channel(blue)
}

/** WCAG contrast ratio between two colors (range 1..21). */
private fun contrastRatio(a: Color, b: Color): Double {
    val la = a.luminance()
    val lb = b.luminance()
    val lighter = maxOf(la, lb)
    val darker = minOf(la, lb)
    return (lighter + 0.05) / (darker + 0.05)
}

/**
 * Returns [on] blended toward the light/dark pole until it clears the WCAG AA
 * 4.5:1 threshold against [container]. Used as a readability safety net on
 * wallpaper-derived (Material You) schemes, whose text colors occasionally
 * come out too close to their backgrounds to read comfortably. Colors that
 * already pass are returned unchanged.
 */
private fun ensureReadable(on: Color, container: Color): Color {
    if (contrastRatio(on, container) >= MIN_TEXT_CONTRAST_RATIO) return on
    // Blend toward whichever pole (white or black) gives the best contrast
    // against the container. One of the poles always clears WCAG AA, so this
    // guarantees the loop below terminates with a readable color.
    val target = if (contrastRatio(Color.White, container) > contrastRatio(Color.Black, container)) {
        Color.White
    } else {
        Color.Black
    }
    var result = on
    for (step in 1..24) {
        result = lerp(on, target, step / 24f)
        if (contrastRatio(result, container) >= MIN_TEXT_CONTRAST_RATIO) break
    }
    return result
}

/**
 * Enforces the WCAG AA text contrast floor on every text role of the scheme,
 * keeping the personalized palette while guaranteeing readable text.
 */
private fun ColorScheme.withAccessibleText(): ColorScheme = copy(
    onSurface = ensureReadable(onSurface, surface),
    onSurfaceVariant = ensureReadable(onSurfaceVariant, surface),
    onPrimary = ensureReadable(onPrimary, primary),
    onPrimaryContainer = ensureReadable(onPrimaryContainer, primaryContainer),
    onSecondary = ensureReadable(onSecondary, secondary),
    onSecondaryContainer = ensureReadable(onSecondaryContainer, secondaryContainer),
    onTertiary = ensureReadable(onTertiary, tertiary),
    onTertiaryContainer = ensureReadable(onTertiaryContainer, tertiaryContainer),
    onError = ensureReadable(onError, error),
    onErrorContainer = ensureReadable(onErrorContainer, errorContainer),
    inverseOnSurface = ensureReadable(inverseOnSurface, inverseSurface)
)

/**
 * ZipGallery theme.
 *
 * @param themeMode forced light / dark / follow-system selection.
 * @param dynamicColor when true (and on Android 12+), uses Material You dynamic
 *   color so the app takes its palette from the user's wallpaper. Text roles are
 *   contrast-checked afterward so the palette stays personal but readable.
 */
@Composable
fun ZipGalleryTheme(
    themeMode: AppThemeMode = AppThemeMode.SYSTEM,
    dynamicColor: Boolean = true,
    content: @Composable () -> Unit
) {
    val context = LocalContext.current
    val darkTheme = when (themeMode) {
        AppThemeMode.DARK -> true
        AppThemeMode.LIGHT -> false
        AppThemeMode.SYSTEM -> isSystemInDarkTheme()
    }
    val colorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val dynamic = if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
            dynamic.withAccessibleText()
        }
        else -> if (darkTheme) DarkColorScheme.withAccessibleText() else LightColorScheme.withAccessibleText()
    }
    MaterialTheme(
        colorScheme = colorScheme,
        content = content
    )
}
